enum ItemActionTypeKeys {
  FETCHING_COLLECTION = 'FETCHING_COLLECTION',
  FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE = 'FETCH_COLLECTION_FAILURE',
  ADD_ITEM = 'ADD_ITEM',
  DELETE_ITEM = 'DELETE_ITEM',
  ITEM_ERROR = 'ITEM_ERROR',
  SET_TAGS = 'SET_TAGS',
}

export default ItemActionTypeKeys
