enum RequestActionTypeKeys {
  REQUEST_OK = 'REQUEST_OK',
  REQUEST_SERVER_ERROR = 'REQUEST_SERVER_ERROR',
  REQUEST_UNPROCESSABLE = 'REUQEST_UNPROCESSABLE',
  REQUEST_UNAUTHORIZED = 'REQUEST_UNAUTHORIZED',
}

export default RequestActionTypeKeys
