enum RequestActionTypeKeys {
  REQUEST_OK = 'REQUEST_OK',
  REQUEST_SERVER_ERROR = 'REQUEST_SERVER_ERROR',
  REQUEST_UNPROCESSABLE = 'REQUEST_UNPROCESSABLE',
  REQUEST_UNAUTHORIZED = 'REQUEST_UNAUTHORIZED',
  REQUEST_UNKNOWN_ERROR = 'REQUEST_UNKNOWN_ERROR',
}

export default RequestActionTypeKeys
