#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only)
if [[ -z "$STAGED_FILES" ]]; then
    exit 0
fi

# Redirect output to stderr.
exec 1>&2

# Helper functions
allow() {
    echo -n "[$1] -> "
    ${@: -1}
    echo "✓"
}

flunk() {
    printf "$*"
    exit 1
}

# The actual assertions
only_ascii_chars() {
    if git rev-parse --verify HEAD >/dev/null 2>&1
    then
        against=HEAD
    else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
    fi
    allownonascii=$(git config --bool hooks.allownonascii)
    if [[ $allownonascii != "true" &&
            $(git diff --staged --name-only --diff-filter=A -z $against |
    LC_ALL=C tr -d '[ -~]\0' | wc -c | tr -d '[:space:]') != 0 ]];
    then
        flunk "Error: Attempt to add a non-ASCII file name. This can cause problems if you want to work with people on other platforms. To be portable it is advisable to rename the file. If you know what you are doing you can disable this check using: git config hooks.allownonascii true"
    fi
}

proper_whitespace() {
    if git rev-parse --verify HEAD >/dev/null 2>&1
    then
        against=HEAD
    else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
    fi
    local whitespace_errors=$(git diff-index --check --cached $against --)
    if [[ ! -z $whitespace_errors ]]; then
        flunk "$whitespace_errors"
    fi
}

backend_has_changed() {
    if [[ ! -z $(echo -e "$STAGED_FILES" | grep backend/) ]]; then
        echo "true"
    fi
}

reject_all_violations() {
    # Run rubocop with autocorrect and re-stage anything it fixes
    RUBOCOP_COMMAND="rubocop -Ra --no-color"
    cd `git rev-parse --show-toplevel`/backend && $RUBOCOP_COMMAND >/dev/null && git update-index --again
    # Any remaining violations will abort the commit
    local violations=$($RUBOCOP_COMMAND | grep -oE '([[:digit:]]+) offense(s?) detected')
    if [[ ! -z $violations ]]; then
        flunk "Error: Attempt to commit with $violations.\n\nRun '$RUBOCOP_COMMAND' in backend and fix the violations before you commit your changes."
    fi
}

# Is this DSL shit just being too clever?
allow "file names" that contain only_ascii_chars
allow "files" that contain proper_whitespace
if [[ $(backend_has_changed) == "true" ]]; then
    allow "rubocop" to enjoy no conflicts but if there are any to reject_all_violations
fi
