enum AuthActionTypeKeys {
  SIGN_IN_PENDING = 'SIGN_IN_PENDING',
  SIGN_IN_FULFILLED = 'SIGN_IN_FULFILLED',
  SIGN_IN_REJECTED = 'SIGN_IN_REJECTED',
  SIGN_OUT = 'SIGN_OUT',
  CREATE_USER_PENDING = 'CREATE_USER_PENDING',
  CREATE_USER_FULFILLED = 'CREATE_USER_FULFILLED',
  CREATE_USER_REJECTED = 'CREATE_USER_REJECTED',
}

export default AuthActionTypeKeys
