enum ItemActionTypeKeys {
  FETCHING_COLLECTION = 'FETCHING_COLLECTION',
  FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE = 'FETCH_COLLECTION_FAILURE',
  ADD_ITEM = 'ADD_ITEM',
  DELETE_ITEM = 'DELETE_ITEM',
  ITEM_ERROR = 'ITEM_ERROR',
  ADD_TAG = 'ADD_TAG',
  REMOVE_TAG = 'REMOVE_TAG',
  CLEAR_TAGS = 'CLEAR_TAGS',
}

export default ItemActionTypeKeys
